---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars_files:
    - "default.config.yml"

  pre_tasks:
    - name: Include optional configuration files.
      include_vars: "{{ item }}"
      with_fileglob:
        - "config.yml"
      tags: always

  roles:
    - { role: system, tags: [packages] }
    - { role: dev-tools/git, when: git, tags: [git, dev-tools] }
    - { role: oefenweb.virtualbox, when: virtualbox, tags: [virtualbox, dev-tools] }
    - { role: oefenweb.vagrant, when: vagrant, tags: [vagrant, dev-tools] }
    - { role: gantsign.oh-my-zsh, when: zsh, tags: [shell, zsh] }
    - { role: oefenweb.chrome, when: chrome, tags: [browser, chrome] }
    - { role: geerlingguy.docker, when: docker, tags: [docker, dev-tools] }
    #- { role: dev-tools/tmuxinator, when: tmuxinator, tags: [tmuxinator, dev-tools] }
    - { role: aeimer.install_bat, when: bat, tags: [bat, dev-tools] }
    - { role: dev-tools/mysql-workbench, when: mysql_workbench }
    - { role: editors/typora, when: typora, tags: [typora, editor, markdown] }
    - { role: dev-tools/pet, when: pet_cli, tags: [dev-tools] }
    - { role: dev-tools/openshift_client, when: openshift_client, tags: [openshift_client, k8s, cloud] }
    - { role: others/insync, when: insync, tags: [insync, drive] }
    - { role: others/chezmoi, when: chezmoi, tags: [chezmoi, dotfiles] }
    - { role: andrewrothstein.go, when: golang, tags: [golang] }
    - { role: dev-tools/footloose, when: footloose, tags: [footloose] }
    - { role: dev-tools/faas-cli, when: faas, tags: [faas] }
    - { role: custom, become: no, tags: [custom, zsh] }
    - { role: others/calibre-ebook, when: calibre, tags: [calibre] }
    - { role: geerlingguy.java, when: java, tags: [java] }
    - { role: dev-tools/azure, when: azure_cli, tags: [azure, azure-cli] }
    - { role: cimon-io.asdf, when: asdf, tags: [asdf] }

  # @todo
  # Install zsh-plugins
  # Install editor * plugins (vscode, phpstorm)
  # Install autotag
  # molotov
  # java
  # hub ?
  # red : https://github.com/antonmedv/red
  # bash-it : https://github.com/Bash-it/bash-it ?

  post_tasks:
    - name: Update .zshrc
      block:
        - name: Add tmux autostart support to zsh
          become: no
          lineinfile:
            path: "{{ lookup('env','HOME') }}/.zshrc"
            insertafter: "source $ZSH/oh-my-zsh.sh"
            line: "ZSH_TMUX_AUTOSTART=true"
          when: tmux and tmux_autostart

        - name: Add autojump support to zsh
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.zshrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - autojump #"
            content: |
              source /usr/share/autojump/autojump.sh
          when: autojump and update_shell_sources

        - name: Add GOPATH and GOBIN
          become: no
          block:
            - name: Create go dir
              with_items:
                - '{{go_dev_path}}'
              file:
                path: '{{item}}'
                state: directory
                mode: '0755'

            - blockinfile:
                path: "{{ lookup('env','HOME') }}/.zshrc"
                marker: "# {mark} ANSIBLE MANAGED BLOCK - golang #"
                content: |
                  {{ golang_govars }}
          when: golang and golang_govars and update_shell_sources

        - name: Add direnv support to zsh
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.zshrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - direnv #"
            content: |
              eval "$(direnv hook zsh)"
          when: direnv and update_shell_sources

        - name: Add azure cli autocompletion to zsh
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.zshrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - azure-cli #"
            content: |
              autoload -U +X bashcompinit && bashcompinit
              source /etc/bash_completion.d/azure-cli
          when: azure_cli and update_shell_sources

        - name: Add custom aliases
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.zshrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - custom_aliases #"
            content: |
              {{ custom_aliases }}
          when: custom_aliases and update_aliases
      when: zsh
      tags: [shell]

    - name: Update .bashrc
      block:
        - name: Add tmux autostart support to bash
          become: no
          lineinfile:
            path: "{{ lookup('env','HOME') }}/.bashrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - tmux autostart #"
            insertafter: "source $ZSH/oh-my-zsh.sh"
            line: "ZSH_TMUX_AUTOSTART=true"
          when: tmux and tmux_autostart

        - name: Add autojump support to bash
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.bashrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - autojump #"
            content: |
              source /usr/share/autojump/autojump.sh
          when: autojump and update_shell_sources

        - name: Add GOPATH and GOBIN
          become: no
          block:
            - name: Create go dir
              with_items:
                - '{{go_dev_path}}'
              file:
                path: '{{item}}'
                state: directory
                mode: '0755'

            - blockinfile:
                path: "{{ lookup('env','HOME') }}/.bashrc"
                marker: "# {mark} ANSIBLE MANAGED BLOCK - golang #"
                content: |
                  {{ golang_govars }}
          when: golang and golang_govars and update_shell_sources

        - name: Add direnv support to bash
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.bashrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - direnv #"
            content: |
              eval "$(direnv hook zsh)"
          when: direnv and update_shell_sources

        - name: Add azure cli autocompletion to bash
          become: no
          blockinfile:
            path: "{{ lookup('env','HOME') }}/.bashrc"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - azure-cli #"
            content: |
              source /etc/bash_completion.d/azure-cli
          when: azure_cli and update_shell_sources

        - name: Add custom aliases
          become: no
          blockinfile:
            create: yes
            path: "{{ lookup('env','HOME') }}/.bash_aliases"
            marker: "# {mark} ANSIBLE MANAGED BLOCK - custom_aliases #"
            content: |
              {{ custom_aliases }}
          when: custom_aliases and update_aliases
      when: not zsh
      tags: [shell]

    - name: Create / Update gitconfig files
      become: no
      tags: [gitconfig]
      blockinfile:
        create: yes
        path: "{{ lookup('env','HOME') }}/{{ item.name }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }} #"
        content: |
          {{ item.value }}
      loop: "{{ gitconfig|flatten(levels=1) }}"
      when: update_gitconfig

    - name: Restart network-manager
      when: openvpn
      service:
        name: openvpn
        state: restarted
