---
- hosts: localhost
  connection: local
  sudo: true

  vars_prompt:
    user_name: "what is your name?"

  vars:
    user: "{{user_name}}"
    packages:
      - tree
      - xclip
      - curl
    plugins:
      - vagrant-hostmanager
      - vagrant-vbguest

  roles:
    - { role: system }
    - { role: dev-tools/git }
    - { role: denkhaus.vagrant, tags: [vagrant, dev-tools] }
    - { role: devbox.oh-my-zsh, tags: [shell, zsh] }
    - { role: devbox.chrome, tags: [browser, chrome] }
    - { role: browsers/firefox }
    - { role: dev-tools/mysql-workbench }
    - { role: others/filezilla }
    - { role: others/xchat }
    - { role: kosssi.phpstorm, tags: [phpstorm, editor] }
