---
- hosts: localhost
  connection: local
  sudo: true

  vars_files:
    - config.yml

  roles:
    - { role: system }
    - { role: dev-tools/git, when: git }
    - { role: denkhaus.vagrant, when: vagrant, tags: [vagrant, dev-tools] }
    - { role: devbox.oh-my-zsh, when: zsh, tags: [shell, zsh] }
    - { role: devbox.chrome, when: chrome, tags: [browser, chrome] }
    - { role: browsers/firefox, when: firefox }
    - { role: dev-tools/mysql-workbench, when: mysql-workbench }
    - { role: others/filezilla, when: filezilla }
    - { role: others/xchat, when: xchat }
    - { role: kosssi.phpstorm, when: phpstorm, tags: [phpstorm, editor] }
