- src: gantsign.oh-my-zsh
  version: "2.2.1"
- src: oefenweb.chrome
  version: "v1.0.33"
- src: oefenweb.virtualbox
- src: oefenweb.vagrant
- src: geerlingguy.docker
- src: aeimer.install_bat
- src: andrewrothstein.go
- src: geerlingguy.java
