---
- hosts: localhost
  connection: local
  sudo: yes

  vars_files:
    - config.yml
  
  tasks:
    - name: Uninstall ruby + Gem
      apt: pkg={{ item }} state=absent
      with_items:
        - gem
        - ruby
