---
# Tasks to install zsh themes
- name: Download zsh-themes
  become: no
  git:
    repo: "{{ item.url }}"
    dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/themes/{{ item.dest }}"
    version: "{{ item.version | default('master') }}"
  loop: "{{ zsh_themes | flatten(levels=1) }}"

- name: Symlink zsh-themes
  file:
    src: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/themes/{{ item.symlink_from }}"
    dest: "{{ lookup('env','HOME') }}/.oh-my-zsh/custom/themes/{{ item.symlink_to }}"
    state: link
  loop: "{{ zsh_themes | flatten(levels=1) }}"
  when:
    - item.symlink | default(False)
