---
- set_fact:
    all_packages: "{{ packages | flatten(levels=1) }}"

- name: Install packages with snaps
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(omit) }}"
  loop: "{{ all_packages }}"
  when: 
    - item.install | default(False)
    - item.install_with == 'snap'

- name: install packages with APT
  tags: system
  apt: pkg={{ item.name }} state=latest update_cache=yes
  loop: "{{ all_packages }}"
  when: 
    - item.install | default(False)
    - item.install_with == 'apt'