---
- name: Add Apt signing key for insync
  apt_key:
    id: ACCAF35C
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - insync
    - drive
    - sync

- name: Install repo for latest insync packages
  apt_repository:
    repo: 'deb http://apt.insync.io/ubuntu {{ ansible_distribution_release }} non-free contrib'
    state: present
    update_cache: yes
  tags:
    - insync
    - drive
    - sync

- name: install insync
  tags:
    - insync
    - drive
    - sync
  apt: pkg=insync state=latest
