galaxy_info:
  author: jygastaud
  description: Install Calibre Ebook
  company: Clever Age
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - calibre
    - ebook
