---
- name: check for install
  become: '{{ footloose_privilege_escalation }}'
  become_user: root
  stat:
    path: '{{ footloose_unarchive_dir }}/footloose'
  changed_when: false
  register: footloose_binary_present

- when: not footloose_binary_present.stat.exists
  block:
    - name: download...
      become: '{{ footloose_privilege_escalation }}'
      become_user: root
      get_url:
        url: '{{ footloose_download_url }}'
        dest: /tmp/{{ footloose_filename }}
        mode: 0644
        # checksum: '{{ footloose_checksum }}'
        timeout: '{{ footloose_download_timeout }}'

    - name: create directory for unarchive if required...
      become: '{{ footloose_privilege_escalation }}'
      become_user: root
      file:
        path: '{{ footloose_unarchive_dir }}'
        state: directory
        mode: 0755

    - name: unarchive
      become: '{{ footloose_privilege_escalation }}'
      become_user: root
      copy:
        remote_src: yes
        src: /tmp/{{ footloose_filename }}
        dest: '{{ footloose_unarchive_dir }}/footloose'
        mode: 0755
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ footloose_filename }}
        state: absent
